=== timzatko/TW-Calc-Website-Events/schema.json
{
    "$id": "https://github.com/timzatko/TW-Calc-Website-Events/tree/master/schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Event",
    "type": "object",
    "properties": {
        "key": {
            "type": "string",
            "pattern": "^[a-z]+[_a-z]*$"
        },
        "name": {
            "type": "string",
            "pattern": "^[ a-zA-Z0-9!?'\",.-]+$"
        },
        "items": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "number"
            }
        },
        "sets": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string",
                "pattern": "^[a-zA-Z0-9_-]+$"
            }
        },
        "quests": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "number"
            }
        },
        "year": {
            "type": "integer",
            "minimum": 0
        },
        "tombola": {
            "type": "integer",
            "minimum": 0
        },
        "forum_url": {
            "type": "string",
            "pattern": "^(https?):\\/\\/[^\\s$.?#].[^\\s]*$"
        },
        "from": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "beta_from": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "to": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "beta_to": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "hidden": {
            "type": "boolean"
        },
        "widget_config": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^[0-9A-F]+$"
            }
        }
    },
    "required": ["key", "year"]
}

=== timzatko/TW-Calc-Website-Events/events/2018_the_true_wild_west.json
{
    "key": "the_true_wild_west",
    "name": "The True Wild West",
    "items": [51008000, 51010000, 51009000, 50992000],
    "sets": ["2018_sale_set_golden_1"],
    "from": "2018-04-26 00:00:00",
    "to": "2018-04-28 00:00:00",
    "year": 2018,
    "forum_url": "https://forum.the-west.net/index.php?threads/the-true-wild-west.57680/"
}

=== timzatko/TW-Calc-Website-Events/events/2021_octoberfest.json
{
    "key": "octoberfest",
    "sets": [
        "oktoberfest_2021_set_10",
        "oktoberfest_2021_set_9",
        "oktoberfest_2021_set_8",
        "oktoberfest_2021_set_7",
        "oktoberfest_2021_set_6",
        "oktoberfest_2021_set_5",
        "oktoberfest_2021_set_4",
        "oktoberfest_2021_set_3",
        "oktoberfest_2021_set_2",
        "oktoberfest_2021_set_1"
    ],
    "year": 2021,
    "tombola": 35,
    "beta_from": "2021-09-07 12:00:00",
    "beta_to": "2021-10-11 11:59:59",
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/oktoberfest-event-2021.4074/#post-40965"
}

=== timzatko/TW-Calc-Website-Events/events/2020_easter.json
{
    "key": "easter",
    "items": [
        51977000,
        51975000,
        51969000,
        51968000,
        51965000,
        51963000,
        51960000,
        51964000,
        51967000,
        51962000,
        51957000,
        51959000,
        51949000,
        51953000,
        51955000,
        51951000,
        51954000,
        51940000,
        51947000,
        51946000,
        51945000,
        51937000,
        51938000,
        51930000,
        51932000,
        51935000,
        51929000,
        51931000,
        51978000,
        51979000,
        51980000,
        51983000,
        51986000,
        51985000,
        51981000,
        51982000
    ],
    "sets": [
        "easter_2020_set_1",
        "easter_2020_set_2",
        "easter_2020_set_3",
        "easter_2020_set_4",
        "easter_2020_set_5",
        "easter_2020_set_6",
        "easter_2020_set_7",
        "easter_2020_set_8"
    ],
    "from": "2020-04-07 00:00:00",
    "to": "2020-04-30 23:59:59",
    "year": 2020,
    "tombola": 28,
    "beta_from": "2020-03-18 10:00:00",
    "beta_to": "2020-04-24 10:00:00"
}

=== timzatko/TW-Calc-Website-Events/events/2025_sports_event.json
{
    "key": "sports_event",
    "name": "Sports Event",
    "items": [54410000, 54403000, 54404000, 54405000, 54406000, 54407000, 54409000],
    "year": 2025,
    "quests": [324],
    "from": "2025-06-12 12:00:00",
    "to": "2025-06-26 12:00:00",
    "beta_from": "2025-06-03 12:00:00",
    "beta_to": "2025-06-26 12:00:00",
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/sports-event-2025.5198/"
}

=== timzatko/TW-Calc-Website-Events/events/2023_fort_event.json
{
    "key": "fort_event",
    "name": "Bent's Fort Event",
    "sets": [],
    "items": [53353000, 53357000, 53354000],
    "year": 2023,
    "quests": [275],
    "from": "2023-06-07 12:00:00",
    "to": "2023-06-21 12:00:00",
    "beta_from": "2023-05-30 12:00:00",
    "beta_to": "2023-06-21 12:00:00",
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/bents-fort-event.4513/"
}

=== timzatko/TW-Calc-Website-Events/events/2019_harvest_time.json
{
    "key": "harvest_time",
    "name": "Harvest time",
    "items": [
        51611000,
        51616000,
        51641000,
        51642000,
        51643000,
        51644000,
        51645000,
        51646000,
        51647000,
        51648000,
        51649000,
        51650000
    ],
    "from": "2019-08-22 00:00:00",
    "to": "2019-09-09 00:00:00",
    "year": 2019,
    "quests": [208],
    "forum_url": "https://forum.the-west.net/index.php?threads/harvest-time.58476/"
}

=== timzatko/TW-Calc-Website-Events/events/2016_octoberfest.json
{
    "key": "octoberfest",
    "items": [
        50207000, 50208000, 50209000, 50211000, 50212000, 50213000, 50214000, 50215000, 50216000, 50217000, 50218000,
        50219000, 50220000, 50221000, 50222000, 50223000, 50224000, 50225000, 50226000, 50227000, 50228000, 50229000,
        50230000, 50231000, 50232000, 50233000, 50234000, 50235000, 50236000, 50237000, 50238000, 50239000, 50240000,
        50241000, 50242000, 50243000, 50244000, 50245000, 50246000, 50247000, 50248000, 50249000, 50250000, 50251000,
        50252000, 50253000, 50254000, 50255000, 50256000, 50257000
    ],
    "sets": [
        "set_oktoberfest_2016_1",
        "set_oktoberfest_2016_1_weapon",
        "set_oktoberfest_2016_2",
        "set_oktoberfest_2016_2_weapon",
        "set_oktoberfest_2016_3",
        "set_oktoberfest_2016_3_weapon",
        "set_oktoberfest_2016_4",
        "set_oktoberfest_2016_5"
    ],
    "from": "2016-09-14 10:00:00",
    "to": "2017-10-06 23:59:59",
    "year": 2016,
    "quests": [155],
    "tombola": 15
}

=== timzatko/TW-Calc-Website-Events/events/2021_may_sale.json
{
    "key": "may_sale",
    "name": "May Sale",
    "items": [51139000, 51140000, 51141000, 51997000, 51998000, 52498000],
    "sets": ["chef_set_1", "chef_set_2", "firefighter_set_1", "firefighter_set_2"],
    "from": "2021-04-30 12:00:00",
    "to": "2021-05-01 12:00:00",
    "year": 2021,
    "beta_from": "2021-04-30 12:00:00",
    "beta_to": "2021-05-01 12:00:00",
    "forum_url": "https://forum.the-west.net/index.php?threads/may-sale-2021.60048/#post-777088"
}
