=== timzatko/TW-Calc-Website-Events/schema.json
{
    "$id": "https://github.com/timzatko/TW-Calc-Website-Events/tree/master/schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Event",
    "type": "object",
    "properties": {
        "key": {
            "type": "string",
            "pattern": "^[a-z]+[_a-z]*$"
        },
        "name": {
            "type": "string",
            "pattern": "^[ a-zA-Z0-9!?'\",.-]+$"
        },
        "items": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "number"
            }
        },
        "sets": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string",
                "pattern": "^[a-zA-Z0-9_-]+$"
            }
        },
        "quests": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "number"
            }
        },
        "year": {
            "type": "integer",
            "minimum": 0
        },
        "tombola": {
            "type": "integer",
            "minimum": 0
        },
        "forum_url": {
            "type": "string",
            "pattern": "^(https?):\\/\\/[^\\s$.?#].[^\\s]*$"
        },
        "from": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "beta_from": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "to": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "beta_to": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "hidden": {
            "type": "boolean"
        },
        "widget_config": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^[0-9A-F]+$"
            }
        }
    },
    "required": ["key", "year"]
}

=== timzatko/TW-Calc-Website-Events/events/2022_halloween_sale.json
{
    "key": "halloween_sale",
    "name": "Halloween Sale",
    "items": [52676000, 52677000, 52678000, 52679000, 52680000, 52681000, 52682000, 52683000, 52684000],
    "year": 2022,
    "quests": [],
    "from": "2022-10-31 12:00:00",
    "to": "2022-11-02 12:00:00",
    "beta_from": "2022-10-31 09:00:00",
    "beta_to": "2022-11-02 09:00:00",
    "forum_url": "https://forum.the-west.net/index.php?threads/halloween-sale-2022.61010/#post-794521"
}

=== timzatko/TW-Calc-Website-Events/events/2019_civil_war_sale.json
{
    "key": "civil_war_sale",
    "name": "Civil War Sale",
    "items": [
        51399000,
        51400000,
        51401000,
        51402000,
        51403000,
        51404000,
        51405000,
        51406000,
        51407000,
        51408000,
        51409000
    ],
    "sets": ["spring_1_2019", "spring_2_2019"],
    "from": "2019-04-14 12:00:00",
    "to": "2019-04-16 12:00:00",
    "year": 2019,
    "forum_url": "https://forum.the-west.net/index.php?threads/civil-war.58359/#post-769019"
}

=== timzatko/TW-Calc-Website-Events/events/2017_dotd.json
{
    "key": "dotd",
    "items": [50736000, 50760000, 50761000, 50762000, 50763000, 50764000, 50765000],
    "sets": [
        "set_dod_2017_1_clothes",
        "set_dod_2017_1_weapons",
        "set_dod_2017_2_animal",
        "set_dod_2017_2_clothes",
        "set_dod_2017_2_weapons",
        "set_dod_2017_3_animal",
        "set_dod_2017_3_clothes"
    ],
    "from": "2017-11-08 11:00:00",
    "to": "2017-11-23 23:59:59",
    "year": 2017,
    "quests": [176],
    "tombola": 17
}

=== timzatko/TW-Calc-Website-Events/events/2023_february_sale.json
{
    "key": "february_sale",
    "name": "February Sale",
    "sets": ["oktoberfest_2022_premium_set_3", "oktoberfest_2022_premium_set_2", "oktoberfest_2022_premium_set_1"],
    "items": [52322000, 52323000],
    "year": 2023,
    "quests": [],
    "from": "2023-02-03 12:00:00",
    "to": "2023-02-05 12:00:00",
    "beta_from": "2023-02-03 09:00:00",
    "beta_to": "2023-02-05 09:00:00",
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/february-2023-sale.4393/"
}

=== timzatko/TW-Calc-Website-Events/events/2022_independence.json
{
    "key": "independence",
    "items": [52931000, 52898000, 52911000, 52915000, 52903000],
    "sets": [
        "independence_day_2022_set_1",
        "independence_day_2022_set_2",
        "independence_day_2022_set_3",
        "independence_day_2022_set_4",
        "independence_day_2022_set_5",
        "independence_day_2022_set_6",
        "independence_day_2022_set_7",
        "independence_day_2022_set_8",
        "independence_day_2022_set_9",
        "independence_day_2022_set_10",
        "independence_day_2022_set_11",
        "independence_day_2022_set_12",
        "independence_day_2022_set_13"
    ],
    "quests": [257],
    "year": 2022,
    "beta_from": "2012-06-29 12:00:00",
    "beta_to": "2012-07-26 12:00:00",
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/independence-day-2022.4237/#post-44201"
}

=== timzatko/TW-Calc-Website-Events/events/2026_independence.json
{
    "key": "independence",
    "name": "Independence Day Event",
    "year": 2026,
    "from": "2026-07-01 12:00:00",
    "to": "2026-07-21 12:00:00",
    "beta_from": "2026-06-23 12:00:00",
    "beta_to": "2026-07-21 12:00:00",
    "sets": [
        "independence_day_2026_set_1",
        "independence_day_2026_set_2",
        "independence_day_2026_set_3",
        "independence_day_2026_set_4",
        "independence_day_2026_set_5",
        "independence_day_2026_set_6",
        "independence_day_2026_set_7",
        "independence_day_2026_set_8",
        "independence_day_2026_set_9",
        "independence_day_2026_set_10",
        "independence_day_2026_set_11",
        "independence_day_2026_set_12",
        "independence_day_2026_set_13"
    ],
    "items": [54856000, 54857000, 54869000, 54870000, 54882000, 54883000, 54902000],
    "quests": [340],
    "tombola": 59,
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/independence-day-2026.5666/"
}

=== timzatko/TW-Calc-Website-Events/events/2026_soccer_event.json
{
    "key": "soccer_event",
    "name": "Soccer Event",
    "year": 2026,
    "from": "2026-06-10 00:00:00",
    "to": "2026-06-24 00:00:00",
    "beta_from": "2026-06-02 00:00:00",
    "beta_to": "2026-06-24 00:00:00",
    "items": [55074000, 55075000, 55076000, 55077000, 55078000, 55079000],
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/soccer-event-2026.5602/"
}

=== timzatko/TW-Calc-Website-Events/events/2024_independence.json
{
    "key": "independence",
    "items": [54028000, 54016000, 54015000, 54033000, 54003000, 54002000, 54029000],
    "sets": [
        "independence_day_2024_set_1",
        "independence_day_2024_set_2",
        "independence_day_2024_set_3",
        "independence_day_2024_set_4",
        "independence_day_2024_set_5",
        "independence_day_2024_set_6",
        "independence_day_2024_set_7",
        "independence_day_2024_set_8",
        "independence_day_2024_set_9",
        "independence_day_2024_set_10",
        "independence_day_2024_set_11",
        "independence_day_2024_set_12",
        "independence_day_2024_set_13"
    ],
    "quests": [],
    "tombola": 44,
    "beta_from": "2024-06-25 12:00:00",
    "beta_to": "2024-07-23 12:00:00",
    "year": 2024,
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/independence-day-2024.4851/"
}
