=== timzatko/TW-Calc-Website-Events/schema.json
{
    "$id": "https://github.com/timzatko/TW-Calc-Website-Events/tree/master/schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Event",
    "type": "object",
    "properties": {
        "key": {
            "type": "string",
            "pattern": "^[a-z]+[_a-z]*$"
        },
        "name": {
            "type": "string",
            "pattern": "^[ a-zA-Z0-9!?'\",.-]+$"
        },
        "items": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "number"
            }
        },
        "sets": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string",
                "pattern": "^[a-zA-Z0-9_-]+$"
            }
        },
        "quests": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "number"
            }
        },
        "year": {
            "type": "integer",
            "minimum": 0
        },
        "tombola": {
            "type": "integer",
            "minimum": 0
        },
        "forum_url": {
            "type": "string",
            "pattern": "^(https?):\\/\\/[^\\s$.?#].[^\\s]*$"
        },
        "from": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "beta_from": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "to": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "beta_to": {
            "type": "string",
            "pattern": "^(\\d{4})-(01|02|03|04|05|06|07|08|09|10|11|12)-(01|02|03|04|05|06|07|08|09|[[1-2][0-9]|30|31) [0-5][0-9]:[0-5][0-9]:[0-5][0-9]$"
        },
        "hidden": {
            "type": "boolean"
        },
        "widget_config": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^[0-9A-F]+$"
            }
        }
    },
    "required": ["key", "year"]
}

=== timzatko/TW-Calc-Website-Events/events/2020_firefighters_sale.json
{
    "key": "firefighters_sale",
    "name": "Firefighters Sale",
    "items": [51997000, 51998000],
    "sets": ["firefighter_set_1", "firefighter_set_2"],
    "from": "2020-05-29 12:00:00",
    "to": "2020-05-31 12:00:00",
    "year": 2020,
    "forum_url": "https://forum.the-west.net/index.php?threads/firefighters-sale.58737/"
}

=== timzatko/TW-Calc-Website-Events/events/2025_harvest_sale.json
{
    "key": "harvest_sale",
    "name": "Harvest Sale",
    "items": [52133000, 52132000, 52131000],
    "year": 2025,
    "quests": [],
    "from": "2025-08-22 12:00:00",
    "to": "2025-08-24 12:00:00",
    "beta_from": "2025-08-22 09:00:00",
    "beta_to": "2025-08-24 09:00:00",
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/harvest-sale-2025.5249/#post-60101"
}

=== timzatko/TW-Calc-Website-Events/events/2022_spring_sale.json
{
    "$schema": "https://raw.githubusercontent.com/timzatko/TW-Calc-Website-Events/master/schema.json",
    "name": "Spring Sale",
    "key": "spring_sale",
    "items": [51467000, 51929000, 51930000, 51931000],
    "sets": [
        "community_event_2020_march",
        "community_event_2020_march_2",
        "eire_set_1",
        "eire_set_2",
        "eire_set_3",
        "summer_spirit"
    ],
    "from": "2022-03-30 12:00:00",
    "to": "2022-04-01 12:00:00",
    "beta_from": "2022-03-30 09:00:00",
    "beta_to": "2022-04-01 09:00:00",
    "year": 2022
}

=== timzatko/TW-Calc-Website-Events/events/2021_winter_event.json
{
    "key": "winter_event",
    "name": "Winter Event",
    "items": [50368000, 52323000, 52322000],
    "sets": ["set_wrightbrothers", "curling_set_1", "curling_set_2"],
    "from": "2021-02-03 12:00:00",
    "to": "2020-02-12 12:00:00",
    "year": 2021,
    "beta_from": "2020-01-23 12:00:00",
    "beta_to": "2020-02-14 12:00:00",
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/winter-event-2020.3502/"
}

=== timzatko/TW-Calc-Website-Events/events/2026_easter.json
{
    "key": "easter",
    "name": "Easter Event",
    "year": 2026,
    "from": "2026-04-01 12:00:00",
    "to": "2026-04-22 12:00:00",
    "beta_from": "2026-03-24 12:00:00",
    "beta_to": "2026-04-24 12:00:00",
    "sets": [
        "easter_2026_set_1",
        "easter_2026_set_2",
        "easter_2026_set_3",
        "easter_2026_set_4",
        "easter_2026_set_5",
        "easter_2026_set_6",
        "easter_2026_set_7",
        "easter_2026_set_8",
        "easter_2026_set_9",
        "easter_2026_set_10",
        "easter_2026_set_11",
        "easter_2026_set_12",
        "easter_2026_set_13"
    ],
    "items": [54781000, 54807000, 54794000],
    "quests": [336],
    "tombola": 58,
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/easter-event-2026.5560/"
}

=== timzatko/TW-Calc-Website-Events/events/2020_lucille_mulhall_sale.json
{
    "key": "lucille_mulhall_sale",
    "name": "Lucille Mulhall Sale",
    "items": [51249000, 51250000, 51467000],
    "sets": ["lucille_animal_set", "lucille_weapon_set", "summer_spirit"],
    "from": "2020-10-27 10:00:00",
    "to": "2020-10-29 10:00:00",
    "year": 2020,
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/lucille-mulhall-sale.3603/"
}

=== timzatko/TW-Calc-Website-Events/events/2019_gift_hunt.json
{
    "key": "gift_hunt",
    "name": "Gift Hunt",
    "items": [
        51816000,
        51818000,
        51819000,
        51820000,
        51821000,
        51822000,
        51824000,
        51825000,
        51826000,
        51827000,
        51828000,
        51829000,
        51830000,
        51831000,
        51832000,
        51833000,
        51834000,
        51835000
    ],
    "from": "2019-12-11 11:00:00",
    "to": "2020-01-02 23:59:59",
    "year": 2019,
    "quests": [214],
    "beta_from": "2019-12-04 00:00:00",
    "beta_to": "2020-01-02 23:59:59",
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/gift-hunt.3485/"
}

=== timzatko/TW-Calc-Website-Events/events/2021_crafting_event.json
{
    "key": "crafting_event",
    "name": "Crafting Event",
    "quests": [240],
    "items": [
      52499000,
      52526000,
      52529000,
      52531000,
      52515000,
      52520000,
      52519000,
      52528000,
      52514000,
      52533000,
      52534000,
      52516000,
      52518000,
      52521000,
      52523000,
      52525000,
      52532000,
      52522000,
      52517000,
      52530000,
      52527000
    ],
    "sets": [],
    "year": 2021,
    "beta_from": "2021-05-13 12:00:00",
    "beta_to": "2021-06-08 12:00:00",
    "forum_url": "https://forum.beta.the-west.net/index.php?threads/crafting-event-2021.4009/#post-39764"
}
